### ISSUE TITLE
Create Voronoi diagram Generator

### ISSUE THREAD

**Issue by zcase** [zcase/labmeat#1]
With the following params:
number of nodes

**Comment by KyleReese** [comment]
Paper on representing cells as Voronoi diagram (might be more detailed than we want to get into) https://link.springer.com/content/pdf/10.1007%2Fs11538-009-9498-3.pdf

**Comment by KyleReese** [comment]
Voronoi generator for protein structures, written in python. Might be useful for us https://academic.oup.com/bioinformatics/article/21/15/3316/195753

**Comment by zcase** [comment]
The generator might be really easy because it is dependent upon numpy arrays I’ll have to submit my example tonight

**Comment by zcase** [comment]
![IMG_6652](https://user-images.githubusercontent.com/15258806/66971952-43612280-f050-11e9-97ba-abe253c021bf.jpg)
![IMG_6656](https://user-images.githubusercontent.com/15258806/66971954-43612280-f050-11e9-9d22-ec62de715de1.jpg)
![IMG_6654](https://user-images.githubusercontent.com/15258806/66971956-43612280-f050-11e9-9eeb-1d7b7a73dfe6.jpg)
![IMG_6655](https://user-images.githubusercontent.com/15258806/66971957-43612280-f050-11e9-8dbe-14611ce0c05a.jpg)
![IMG_6651](https://user-images.githubusercontent.com/15258806/66971958-43612280-f050-11e9-90cc-c17791dbcd2b.jpg)
![IMG_6653](https://user-images.githubusercontent.com/15258806/66971959-43f9b900-f050-11e9-9a3b-43297617b3f9.jpg)

**Comment by zcase** [comment]
Look for planar graph
