### ISSUE TITLE
Transfer Dr. Flann Equations into Python

### ISSUE THREAD

**Issue by zcase** [zcase/labmeat#2]
Convert the equations used in Dr. Flann's paper into python code/functions

**Comment by zcase** [comment]
Solvers for couple of linear equations, ordinarily diff equations, partial diff equations ODSolve PDSolve

**Comment by KyleReese** [comment]
SymPy is probably our best bet 

https://docs.sympy.org/latest/modules/solvers/ode.html#ode-docs
https://docs.sympy.org/latest/modules/solvers/pde.html#pde-docs

**Comment by KyleReese** [comment]
Diffusion original code https://github.com/hplgit/fdm-book/blob/master/src/diffu/diffu2D_u0.py
